// TEKNIK Unified Control Catalog — single source of truth for agent checks, scoring, portals and report.
// Served to the browser via GET /api/compliance/catalog. Edit here only.
export const catalog = {
  "version": "2026.09.1",
  "issuer": "TEKNIK (TNB Consulting Group, LLC)",
  "frameworks": {
    "hipaa": { "name": "HIPAA Security Rule", "cite": "45 CFR Part 164, Subpart C (164.308–164.316), NIST SP 800-66r2" },
    "pci":   { "name": "PCI DSS v4.0.1", "cite": "PCI Security Standards Council, Requirements 1–12" },
    "csf":   { "name": "NIST CSF 2.0", "cite": "NIST Cybersecurity Framework 2.0 (Feb 2024)" },
    "n171":  { "name": "NIST SP 800-171 Rev. 2", "cite": "Protecting CUI in Nonfederal Systems" },
    "cis":   { "name": "CIS Microsoft Windows 10/11 Benchmark", "cite": "CIS Level 1 recommendations unless noted" }
  },
  "severityWeight": { "critical": 10, "high": 6, "medium": 3, "low": 1 },
  "scoring": {
    "technicalShare": 0.6,
    "administrativeShare": 0.4,
    "criticalFailCap": 69,
    "grades": [ [90, "A"], [80, "B"], [70, "C"], [60, "D"], [0, "F"] ]
  },
  "controls": [
    { "id": "EP-01", "domain": "Endpoint Protection", "type": "automated", "check": "av_realtime", "severity": "critical",
      "title": "Anti-malware installed and real-time protection enabled",
      "description": "A supported anti-malware engine (Microsoft Defender or third-party registered with Windows Security Center) is present, running, and performing real-time scanning.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["5.2.1", "5.3.1"], "csf": ["PR.PS-01", "DE.CM-09"], "n171": ["3.14.2", "3.14.4"], "cis": ["18.10.42.10"] },
      "remediation": { "summary": "Enable Microsoft Defender real-time protection (or the managed third-party AV) and enforce via policy.",
        "script": "Set-MpPreference -DisableRealtimeMonitoring $false\nSet-MpPreference -DisableIOAVProtection $false\nSet-MpPreference -DisableBehaviorMonitoring $false\nStart-Service WinDefend -ErrorAction SilentlyContinue" } },
    { "id": "EP-02", "domain": "Endpoint Protection", "type": "automated", "check": "av_signatures_fresh", "severity": "high",
      "title": "Anti-malware signatures updated within 3 days",
      "description": "Definition/intelligence updates are current. PCI DSS 5.2.1 and HIPAA 164.308(a)(5)(ii)(B) require the solution to be kept current.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["5.2.1", "5.2.3"], "csf": ["PR.PS-02"], "n171": ["3.14.4"], "cis": ["18.10.42.5"] },
      "remediation": { "summary": "Force a signature update and verify the update source is reachable.",
        "script": "Update-MpSignature -ErrorAction SilentlyContinue\nSet-MpPreference -SignatureUpdateInterval 4" } },
    { "id": "EP-03", "domain": "Endpoint Protection", "type": "automated", "check": "av_tamper_protection", "severity": "high",
      "title": "Tamper Protection enabled",
      "description": "Prevents local or malicious modification of anti-malware settings.",
      "frameworks": { "hipaa": ["164.312(c)(1)"], "pci": ["5.3.5"], "csf": ["PR.PS-01"], "n171": ["3.14.2"], "cis": ["18.10.42.8"] },
      "remediation": { "summary": "Enable Tamper Protection via Intune / Defender for Endpoint, or locally in Windows Security > Virus & threat protection settings.", "manual": "Tamper Protection cannot be enabled by script on unmanaged devices by design. Enable it in Windows Security or via Intune endpoint security policy." } },
    { "id": "EP-04", "domain": "Endpoint Protection", "type": "automated", "check": "av_cloud_protection", "severity": "medium",
      "title": "Cloud-delivered protection and sample submission configured",
      "description": "MAPS cloud protection provides near-real-time detection of new threats.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["5.2.1"], "csf": ["DE.CM-09"], "n171": ["3.14.2"], "cis": ["18.10.42.5.1"] },
      "remediation": { "summary": "Enable MAPS advanced membership.", "script": "Set-MpPreference -MAPSReporting Advanced\nSet-MpPreference -SubmitSamplesConsent SendSafeSamples" } },
    { "id": "EP-05", "domain": "Endpoint Protection", "type": "automated", "check": "av_last_full_scan", "severity": "medium",
      "title": "Periodic (full or quick) scan completed within 7 days",
      "description": "PCI DSS 5.3.2 requires periodic scans; HIPAA requires procedures for guarding against malicious software.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["5.3.2"], "csf": ["DE.CM-09"], "n171": ["3.14.5"], "cis": ["18.10.42.13"] },
      "remediation": { "summary": "Schedule a daily quick scan and weekly full scan.", "script": "Set-MpPreference -ScanScheduleQuickScanTime 120\nSet-MpPreference -ScanParameters 2 -ScanScheduleDay Everyday -ScanScheduleTime 02:00:00\nStart-MpScan -ScanType QuickScan -ErrorAction SilentlyContinue" } },
    { "id": "EP-06", "domain": "Endpoint Protection", "type": "automated", "check": "asr_rules", "severity": "medium",
      "title": "Attack Surface Reduction rules enforced (core set)",
      "description": "Blocks Office child processes, credential theft from LSASS, executable content from email, and obfuscated scripts.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["5.2.1", "6.4.1"], "csf": ["PR.PS-05"], "n171": ["3.13.13", "3.14.2"], "cis": ["18.10.42.6.1.2"] },
      "remediation": { "summary": "Enable the core ASR rule set in block mode.",
        "script": "$rules = @('D4F940AB-401B-4EFC-AADC-AD5F3C50688A','3B576869-A4EC-4529-8536-B80A7769E899','BE9BA2D9-53EA-4CDC-84E5-9B1EEEE46550','9E6C4E1F-7D60-472F-BA1A-A39EF669E4B2','5BEB7EFE-FD9A-4556-801D-275E5FFC04CC','D3E037E1-3EB8-44C8-A917-57927947596D','26190899-1602-49E8-8B27-EB1D0A1CE869','E6DB77E5-3DF2-4CF1-B95A-636979351E5B')\nforeach ($r in $rules) { Add-MpPreference -AttackSurfaceReductionRules_Ids $r -AttackSurfaceReductionRules_Actions Enabled }" } },
    { "id": "EP-07", "domain": "Endpoint Protection", "type": "automated", "check": "smartscreen", "severity": "low",
      "title": "Microsoft Defender SmartScreen enabled for apps and browsers",
      "description": "Warns or blocks unrecognized downloads and phishing sites.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["5.4.1"], "csf": ["PR.PS-05"], "n171": ["3.14.2"], "cis": ["18.10.76.2.1"] },
      "remediation": { "summary": "Enable SmartScreen and require approval for unrecognized apps.",
        "script": "New-Item 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System' EnableSmartScreen 1 -Type DWord\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System' ShellSmartScreenLevel 'Block' -Type String" } },

    { "id": "ENC-01", "domain": "Encryption", "type": "automated", "check": "bitlocker_os", "severity": "critical",
      "title": "Operating system drive encrypted (BitLocker fully encrypted, protection on)",
      "description": "Full-disk encryption renders ePHI/cardholder data unreadable if the device is lost or stolen — the HIPAA breach safe-harbor condition.",
      "frameworks": { "hipaa": ["164.312(a)(2)(iv)", "164.312(e)(2)(ii)"], "pci": ["3.5.1", "3.5.1.2"], "csf": ["PR.DS-01"], "n171": ["3.13.11", "3.13.16"], "cis": ["18.10.9.1.x"] },
      "remediation": { "summary": "Enable BitLocker with TPM protector and escrow the recovery key to Entra ID/AD.",
        "script": "if ((Get-BitLockerVolume -MountPoint $env:SystemDrive).ProtectionStatus -ne 'On') {\n  Enable-BitLocker -MountPoint $env:SystemDrive -EncryptionMethod XtsAes256 -TpmProtector -UsedSpaceOnly -SkipHardwareTest\n  Add-BitLockerKeyProtector -MountPoint $env:SystemDrive -RecoveryPasswordProtector\n  $kp = (Get-BitLockerVolume -MountPoint $env:SystemDrive).KeyProtector | ? KeyProtectorType -eq 'RecoveryPassword'\n  try { BackupToAAD-BitLockerKeyProtector -MountPoint $env:SystemDrive -KeyProtectorId $kp.KeyProtectorId } catch { Backup-BitLockerKeyProtector -MountPoint $env:SystemDrive -KeyProtectorId $kp.KeyProtectorId -ErrorAction SilentlyContinue }\n}" } },
    { "id": "ENC-02", "domain": "Encryption", "type": "automated", "check": "bitlocker_fixed", "severity": "high",
      "title": "All fixed data drives encrypted",
      "description": "Secondary internal volumes must also be encrypted.",
      "frameworks": { "hipaa": ["164.312(a)(2)(iv)"], "pci": ["3.5.1"], "csf": ["PR.DS-01"], "n171": ["3.13.16"], "cis": ["18.10.9.1.x"] },
      "remediation": { "summary": "Enable BitLocker with auto-unlock on each fixed data drive.",
        "script": "Get-BitLockerVolume | ? { $_.VolumeType -eq 'Data' -and $_.ProtectionStatus -ne 'On' } | % { Enable-BitLocker -MountPoint $_.MountPoint -EncryptionMethod XtsAes256 -RecoveryPasswordProtector -UsedSpaceOnly; Enable-BitLockerAutoUnlock -MountPoint $_.MountPoint }" } },
    { "id": "ENC-03", "domain": "Encryption", "type": "automated", "check": "tpm_ready", "severity": "medium",
      "title": "TPM 2.0 present and ready",
      "description": "Hardware root of trust for BitLocker, Windows Hello, and measured boot.",
      "frameworks": { "hipaa": ["164.312(a)(2)(iv)"], "pci": ["3.5.1"], "csf": ["PR.DS-01"], "n171": ["3.13.11"], "cis": [] },
      "remediation": { "summary": "Enable/clear TPM in UEFI firmware. Devices without TPM 2.0 should be scheduled for replacement.", "manual": "Firmware change — cannot be scripted remotely." } },
    { "id": "ENC-04", "domain": "Encryption", "type": "automated", "check": "secure_boot", "severity": "medium",
      "title": "UEFI Secure Boot enabled",
      "description": "Prevents boot-level malware and unsigned bootloaders.",
      "frameworks": { "hipaa": ["164.312(c)(1)"], "pci": ["2.2.1"], "csf": ["PR.PS-01"], "n171": ["3.13.11"], "cis": [] },
      "remediation": { "summary": "Enable Secure Boot in UEFI (requires GPT disk / UEFI mode).", "manual": "Firmware change." } },
    { "id": "ENC-05", "domain": "Encryption", "type": "automated", "check": "removable_storage_policy", "severity": "medium",
      "title": "Removable storage write access controlled or encrypted (BitLocker To Go)",
      "description": "Prevents unencrypted ePHI/CHD from leaving on USB media.",
      "frameworks": { "hipaa": ["164.310(d)(1)", "164.312(a)(2)(iv)"], "pci": ["3.5.1", "9.4.1"], "csf": ["PR.DS-01", "PR.AA-06"], "n171": ["3.8.7", "3.8.8"], "cis": ["18.10.9.3.x"] },
      "remediation": { "summary": "Require BitLocker To Go for writes to removable drives.",
        "script": "New-Item 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\FVE' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\FVE' RDVDenyWriteAccess 1 -Type DWord\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\FVE' RDVDenyCrossOrg 0 -Type DWord" } },

    { "id": "PATCH-01", "domain": "Patch Management", "type": "automated", "check": "os_supported", "severity": "critical",
      "title": "Operating system is a supported, in-service version",
      "description": "Windows 10 reached end of support 14 Oct 2025 (unless ESU-enrolled). Unsupported OS receives no security fixes.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)", "164.308(a)(1)(ii)(A)"], "pci": ["6.3.3", "12.3.4"], "csf": ["ID.AM-08", "PR.PS-02"], "n171": ["3.14.1"], "cis": [] },
      "remediation": { "summary": "Upgrade to Windows 11 (or enroll in Windows 10 ESU as a stop-gap) or replace the device.", "manual": "OS upgrade / hardware refresh." } },
    { "id": "PATCH-02", "domain": "Patch Management", "type": "automated", "check": "os_patch_age", "severity": "high",
      "title": "Latest cumulative update installed within 30 days",
      "description": "PCI DSS 6.3.3 requires critical patches within one month of release.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["6.3.3"], "csf": ["PR.PS-02"], "n171": ["3.14.1"], "cis": ["18.10.93.x"] },
      "remediation": { "summary": "Install pending updates and enroll device in managed patching (Intune/RMM).",
        "script": "Install-PackageProvider NuGet -Force -ErrorAction SilentlyContinue | Out-Null\nInstall-Module PSWindowsUpdate -Force -ErrorAction SilentlyContinue\nImport-Module PSWindowsUpdate\nGet-WindowsUpdate -AcceptAll -Install -IgnoreReboot" } },
    { "id": "PATCH-03", "domain": "Patch Management", "type": "automated", "check": "pending_reboot", "severity": "low",
      "title": "No pending reboot for installed updates",
      "description": "Updates are not effective until the device restarts.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["6.3.3"], "csf": ["PR.PS-02"], "n171": ["3.14.1"], "cis": [] },
      "remediation": { "summary": "Schedule a restart outside business hours.", "script": "shutdown /r /t 600 /c \"TEKNIK compliance: restarting to complete security updates\"" } },
    { "id": "PATCH-04", "domain": "Patch Management", "type": "automated", "check": "wu_service", "severity": "medium",
      "title": "Windows Update service enabled and not deferred beyond policy",
      "description": "Update service must not be disabled; quality updates deferred no more than 7 days.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["6.3.3"], "csf": ["PR.PS-02"], "n171": ["3.14.1"], "cis": ["18.10.93.4.1"] },
      "remediation": { "summary": "Re-enable the Windows Update service and clear excessive deferrals.",
        "script": "Set-Service wuauserv -StartupType Manual; Start-Service wuauserv\nRemove-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate' -Name DeferQualityUpdatesPeriodInDays -ErrorAction SilentlyContinue" } },
    { "id": "PATCH-05", "domain": "Patch Management", "type": "automated", "check": "eol_software", "severity": "high",
      "title": "No end-of-life or high-risk software installed",
      "description": "Detects unsupported runtimes and applications (e.g., Java 8 public, Adobe Flash, Office 2013/2016 without support, Python 2, legacy Adobe Reader, unmanaged remote-access tools).",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(A)"], "pci": ["6.3.3", "12.3.4"], "csf": ["ID.AM-08"], "n171": ["3.4.1", "3.14.1"], "cis": [] },
      "remediation": { "summary": "Uninstall or upgrade the flagged software; standardize on a managed remote-access tool.", "manual": "Review flagged list in findings detail and remove via Add/Remove Programs or RMM." } },

    { "id": "IAM-01", "domain": "Identity & Access", "type": "automated", "check": "local_admins", "severity": "high",
      "title": "Local Administrators group limited to managed accounts",
      "description": "Standard users must not run as local admin. Only the IT-managed admin account and MSP break-glass account should be members.",
      "frameworks": { "hipaa": ["164.308(a)(3)(i)", "164.308(a)(4)(ii)(B)", "164.312(a)(1)"], "pci": ["7.2.1", "7.2.2"], "csf": ["PR.AA-05"], "n171": ["3.1.5", "3.1.6"], "cis": [] },
      "remediation": { "summary": "Remove day-to-day user accounts from Administrators; deploy LAPS for the local admin.", "manual": "Review the membership list in findings and remove with: Remove-LocalGroupMember -Group Administrators -Member '<user>'" } },
    { "id": "IAM-02", "domain": "Identity & Access", "type": "automated", "check": "guest_disabled", "severity": "high",
      "title": "Guest account disabled",
      "description": "The built-in Guest account allows anonymous, unattributable access.",
      "frameworks": { "hipaa": ["164.312(a)(2)(i)", "164.312(d)"], "pci": ["8.2.1", "8.2.2"], "csf": ["PR.AA-01"], "n171": ["3.1.1", "3.5.1"], "cis": ["2.3.1.1"] },
      "remediation": { "summary": "Disable the Guest account.", "script": "Disable-LocalUser -Name Guest -ErrorAction SilentlyContinue" } },
    { "id": "IAM-03", "domain": "Identity & Access", "type": "automated", "check": "builtin_admin", "severity": "medium",
      "title": "Built-in Administrator (RID 500) disabled or renamed",
      "description": "Reduces exposure to password-spray and pass-the-hash targeting the well-known account.",
      "frameworks": { "hipaa": ["164.312(a)(2)(i)"], "pci": ["2.2.2", "8.2.2"], "csf": ["PR.AA-01"], "n171": ["3.5.1"], "cis": ["2.3.1.1", "2.3.1.5"] },
      "remediation": { "summary": "Disable the built-in Administrator after a LAPS-managed admin exists.", "script": "$rid500 = Get-LocalUser | ? { $_.SID -like 'S-1-5-21-*-500' }\nif ($rid500 -and $rid500.Enabled) { Disable-LocalUser -Name $rid500.Name }" } },
    { "id": "IAM-04", "domain": "Identity & Access", "type": "automated", "check": "blank_passwords", "severity": "critical",
      "title": "No enabled accounts with blank or non-required passwords",
      "description": "Accounts with PasswordRequired=false permit logon without authentication.",
      "frameworks": { "hipaa": ["164.312(d)"], "pci": ["8.3.1"], "csf": ["PR.AA-03"], "n171": ["3.5.2"], "cis": [] },
      "remediation": { "summary": "Set a password and require one on every enabled account.", "manual": "Set-LocalUser -Name '<user>' -PasswordNeverExpires $false; net user <user> /passwordreq:yes" } },
    { "id": "IAM-05", "domain": "Identity & Access", "type": "automated", "check": "pw_min_length", "severity": "high",
      "title": "Minimum password length ≥ 12 characters",
      "description": "PCI DSS v4.0 8.3.6 requires 12+ characters (or 8 if system cannot support 12).",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(D)"], "pci": ["8.3.6"], "csf": ["PR.AA-01"], "n171": ["3.5.7"], "cis": ["1.1.4"] },
      "remediation": { "summary": "Set minimum length to 12 (14 recommended).", "script": "net accounts /minpwlen:14" } },
    { "id": "IAM-06", "domain": "Identity & Access", "type": "automated", "check": "pw_complexity", "severity": "medium",
      "title": "Password complexity enforced",
      "description": "Requires mixed character classes (PCI 8.3.6 numeric + alphabetic).",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(D)"], "pci": ["8.3.6"], "csf": ["PR.AA-01"], "n171": ["3.5.7"], "cis": ["1.1.5"] },
      "remediation": { "summary": "Enable complexity via local security policy.",
        "script": "$cfg = \"$env:TEMP\\secpol.cfg\"; secedit /export /cfg $cfg | Out-Null\n(Get-Content $cfg) -replace 'PasswordComplexity = 0','PasswordComplexity = 1' | Set-Content $cfg\nsecedit /configure /db \"$env:TEMP\\secpol.sdb\" /cfg $cfg /areas SECURITYPOLICY | Out-Null" } },
    { "id": "IAM-07", "domain": "Identity & Access", "type": "automated", "check": "pw_max_age", "severity": "medium",
      "title": "Maximum password age ≤ 90 days (or risk-based rotation documented)",
      "description": "PCI 8.3.9 requires 90-day rotation where passwords are the only factor.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(D)"], "pci": ["8.3.9"], "csf": ["PR.AA-01"], "n171": ["3.5.8"], "cis": ["1.1.2"] },
      "remediation": { "summary": "Set maximum password age to 90 days.", "script": "net accounts /maxpwage:90" } },
    { "id": "IAM-08", "domain": "Identity & Access", "type": "automated", "check": "pw_history", "severity": "low",
      "title": "Password history ≥ 4 remembered",
      "description": "Prevents immediate reuse of previous passwords (PCI 8.3.7).",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(D)"], "pci": ["8.3.7"], "csf": ["PR.AA-01"], "n171": ["3.5.8"], "cis": ["1.1.1"] },
      "remediation": { "summary": "Remember 24 previous passwords.", "script": "net accounts /uniquepw:24" } },
    { "id": "IAM-09", "domain": "Identity & Access", "type": "automated", "check": "lockout_threshold", "severity": "high",
      "title": "Account lockout threshold ≤ 10 invalid attempts",
      "description": "PCI 8.3.4 requires lockout after no more than 10 attempts; lockout for 30 minutes or until reset.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(C)", "164.312(a)(2)(i)"], "pci": ["8.3.4"], "csf": ["PR.AA-03"], "n171": ["3.1.8"], "cis": ["1.2.2"] },
      "remediation": { "summary": "Lockout after 5 attempts, 30-minute duration.", "script": "net accounts /lockoutthreshold:5 /lockoutduration:30 /lockoutwindow:30" } },
    { "id": "IAM-10", "domain": "Identity & Access", "type": "automated", "check": "lockout_duration", "severity": "medium",
      "title": "Account lockout duration ≥ 30 minutes",
      "description": "PCI 8.3.4.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(C)"], "pci": ["8.3.4"], "csf": ["PR.AA-03"], "n171": ["3.1.8"], "cis": ["1.2.1"] },
      "remediation": { "summary": "Set lockout duration to 30 minutes.", "script": "net accounts /lockoutduration:30" } },
    { "id": "IAM-11", "domain": "Identity & Access", "type": "automated", "check": "screen_lock", "severity": "high",
      "title": "Automatic screen lock ≤ 15 minutes with password on resume",
      "description": "PCI 8.2.8 (15 min idle) and HIPAA workstation security / automatic logoff.",
      "frameworks": { "hipaa": ["164.310(b)", "164.312(a)(2)(iii)"], "pci": ["8.2.8"], "csf": ["PR.AA-06"], "n171": ["3.1.10", "3.1.11"], "cis": ["19.1.3.x"] },
      "remediation": { "summary": "Enforce 10-minute inactivity lock machine-wide.",
        "script": "New-Item 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop' ScreenSaveActive '1'\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop' ScreenSaverIsSecure '1'\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop' ScreenSaveTimeOut '600'\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop' SCRNSAVE.EXE 'scrnsave.scr'\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' InactivityTimeoutSecs 600 -Type DWord" } },
    { "id": "IAM-12", "domain": "Identity & Access", "type": "automated", "check": "uac_enabled", "severity": "high",
      "title": "User Account Control enabled at default or higher",
      "description": "UAC prevents silent privilege elevation.",
      "frameworks": { "hipaa": ["164.312(a)(1)"], "pci": ["7.2.1"], "csf": ["PR.AA-05"], "n171": ["3.1.7"], "cis": ["2.3.17.1", "2.3.17.6"] },
      "remediation": { "summary": "Re-enable UAC.", "script": "Set-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' EnableLUA 1 -Type DWord\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' ConsentPromptBehaviorAdmin 2 -Type DWord\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' PromptOnSecureDesktop 1 -Type DWord" } },
    { "id": "IAM-13", "domain": "Identity & Access", "type": "automated", "check": "autologon", "severity": "critical",
      "title": "Automatic logon disabled (no stored DefaultPassword)",
      "description": "AutoAdminLogon stores a plaintext password in the registry and bypasses authentication.",
      "frameworks": { "hipaa": ["164.312(d)"], "pci": ["8.3.1", "8.3.2"], "csf": ["PR.AA-03"], "n171": ["3.5.2", "3.5.10"], "cis": ["18.4.1"] },
      "remediation": { "summary": "Disable AutoAdminLogon and remove stored password.", "script": "$k='HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon'\nSet-ItemProperty $k AutoAdminLogon '0'\nRemove-ItemProperty $k DefaultPassword -ErrorAction SilentlyContinue" } },
    { "id": "IAM-14", "domain": "Identity & Access", "type": "automated", "check": "stale_local_accounts", "severity": "medium",
      "title": "No enabled local accounts inactive > 90 days",
      "description": "PCI 8.2.6 requires removal/disable of inactive accounts within 90 days.",
      "frameworks": { "hipaa": ["164.308(a)(3)(ii)(C)"], "pci": ["8.2.6"], "csf": ["PR.AA-01"], "n171": ["3.5.6"], "cis": [] },
      "remediation": { "summary": "Disable listed inactive accounts.", "manual": "Disable-LocalUser -Name '<user>' for each account in findings detail." } },
    { "id": "IAM-15", "domain": "Identity & Access", "type": "automated", "check": "laps", "severity": "medium",
      "title": "Local admin password managed (Windows LAPS)",
      "description": "Rotates and escrows the local admin password so it is unique per device.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(D)"], "pci": ["2.2.2", "8.3.5", "8.6.3"], "csf": ["PR.AA-01"], "n171": ["3.5.2"], "cis": ["18.9.25.x"] },
      "remediation": { "summary": "Enable Windows LAPS via Intune/GPO with Entra ID or AD backup.", "manual": "Policy deployment — configure LAPS backup directory and password settings in Intune Endpoint Security > Account protection." } },
    { "id": "IAM-16", "domain": "Identity & Access", "type": "automated", "check": "domain_or_entra_joined", "severity": "medium",
      "title": "Device joined to Entra ID or Active Directory (centrally managed identity)",
      "description": "Standalone workgroup devices cannot enforce centralized policy, MFA, or offboarding.",
      "frameworks": { "hipaa": ["164.308(a)(3)(ii)(C)", "164.308(a)(4)"], "pci": ["7.2.4", "8.2.4"], "csf": ["PR.AA-01", "ID.AM-01"], "n171": ["3.1.1"], "cis": [] },
      "remediation": { "summary": "Join the device to Entra ID and enroll in Intune.", "manual": "Settings > Accounts > Access work or school > Join Entra ID." } },

    { "id": "NET-01", "domain": "Network Security", "type": "automated", "check": "firewall_all_profiles", "severity": "critical",
      "title": "Windows Firewall enabled on Domain, Private, and Public profiles",
      "description": "Host firewall with default inbound block on every profile.",
      "frameworks": { "hipaa": ["164.312(a)(1)", "164.312(e)(1)"], "pci": ["1.2.1", "1.5.1"], "csf": ["PR.IR-01"], "n171": ["3.13.1", "3.13.6"], "cis": ["9.1.1", "9.2.1", "9.3.1"] },
      "remediation": { "summary": "Enable all profiles with inbound block default.", "script": "Set-NetFirewallProfile -Profile Domain,Private,Public -Enabled True -DefaultInboundAction Block -DefaultOutboundAction Allow" } },
    { "id": "NET-02", "domain": "Network Security", "type": "automated", "check": "firewall_logging", "severity": "low",
      "title": "Firewall dropped-packet logging enabled",
      "description": "Supports incident investigation (PCI 10.2, CIS 9.x.5).",
      "frameworks": { "hipaa": ["164.312(b)"], "pci": ["10.2.1"], "csf": ["DE.CM-01"], "n171": ["3.3.1"], "cis": ["9.1.7", "9.2.7", "9.3.7"] },
      "remediation": { "summary": "Log dropped packets, 16 MB log.", "script": "Set-NetFirewallProfile -Profile Domain,Private,Public -LogBlocked True -LogMaxSizeKilobytes 16384" } },
    { "id": "NET-03", "domain": "Network Security", "type": "automated", "check": "smbv1_disabled", "severity": "critical",
      "title": "SMBv1 protocol removed/disabled",
      "description": "SMBv1 is the vector for WannaCry/NotPetya-class attacks and is deprecated by Microsoft.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(B)"], "pci": ["2.2.4", "2.2.5"], "csf": ["PR.PS-01"], "n171": ["3.4.6", "3.4.7"], "cis": ["18.4.3"] },
      "remediation": { "summary": "Remove the SMB1 feature.", "script": "Disable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol -NoRestart -ErrorAction SilentlyContinue\nSet-SmbServerConfiguration -EnableSMB1Protocol $false -Force" } },
    { "id": "NET-04", "domain": "Network Security", "type": "automated", "check": "smb_signing", "severity": "medium",
      "title": "SMB signing required (client and server)",
      "description": "Mitigates NTLM relay attacks.",
      "frameworks": { "hipaa": ["164.312(c)(1)", "164.312(e)(2)(i)"], "pci": ["2.2.7", "4.2.1"], "csf": ["PR.DS-02"], "n171": ["3.13.8"], "cis": ["2.3.8.1", "2.3.9.2"] },
      "remediation": { "summary": "Require SMB signing.", "script": "Set-SmbClientConfiguration -RequireSecuritySignature $true -Force\nSet-SmbServerConfiguration -RequireSecuritySignature $true -Force" } },
    { "id": "NET-05", "domain": "Network Security", "type": "automated", "check": "llmnr_disabled", "severity": "medium",
      "title": "LLMNR and NetBIOS name resolution disabled",
      "description": "Prevents Responder-style credential capture on the LAN.",
      "frameworks": { "hipaa": ["164.312(e)(1)"], "pci": ["2.2.4"], "csf": ["PR.PS-01"], "n171": ["3.13.1"], "cis": ["18.6.4.1"] },
      "remediation": { "summary": "Disable LLMNR via policy and NetBIOS over TCP/IP on all adapters.",
        "script": "New-Item 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient' EnableMulticast 0 -Type DWord\nGet-ChildItem 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NetBT\\Parameters\\Interfaces' | % { Set-ItemProperty $_.PSPath NetbiosOptions 2 }" } },
    { "id": "NET-06", "domain": "Network Security", "type": "automated", "check": "rdp_secure", "severity": "high",
      "title": "Remote Desktop disabled, or enabled only with NLA and firewall scoping",
      "description": "Exposed RDP without NLA is a leading ransomware entry point.",
      "frameworks": { "hipaa": ["164.312(a)(1)", "164.312(d)"], "pci": ["2.2.4", "8.4.3"], "csf": ["PR.AA-03", "PR.IR-01"], "n171": ["3.1.12", "3.1.13"], "cis": ["18.10.57.3.9.x"] },
      "remediation": { "summary": "Disable RDP on workstations, or require NLA.",
        "script": "Set-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server' fDenyTSConnections 1 -Type DWord\nSet-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' UserAuthentication 1 -Type DWord\nDisable-NetFirewallRule -DisplayGroup 'Remote Desktop' -ErrorAction SilentlyContinue" } },
    { "id": "NET-07", "domain": "Network Security", "type": "automated", "check": "remote_registry", "severity": "low",
      "title": "Remote Registry service disabled",
      "description": "Unneeded remote management surface on workstations.",
      "frameworks": { "hipaa": ["164.312(a)(1)"], "pci": ["2.2.4"], "csf": ["PR.PS-01"], "n171": ["3.4.6"], "cis": ["5.x"] },
      "remediation": { "summary": "Disable the service.", "script": "Stop-Service RemoteRegistry -ErrorAction SilentlyContinue; Set-Service RemoteRegistry -StartupType Disabled" } },
    { "id": "NET-08", "domain": "Network Security", "type": "automated", "check": "winrm_unencrypted", "severity": "medium",
      "title": "WinRM does not allow unencrypted traffic or Basic auth",
      "description": "Prevents credential exposure over remote management.",
      "frameworks": { "hipaa": ["164.312(e)(1)"], "pci": ["2.2.7", "8.3.2"], "csf": ["PR.DS-02"], "n171": ["3.13.8"], "cis": ["18.10.89.1.1", "18.10.89.2.1"] },
      "remediation": { "summary": "Disable Basic auth and unencrypted WinRM.", "script": "Set-Item WSMan:\\localhost\\Service\\AllowUnencrypted $false -ErrorAction SilentlyContinue\nSet-Item WSMan:\\localhost\\Service\\Auth\\Basic $false -ErrorAction SilentlyContinue\nSet-Item WSMan:\\localhost\\Client\\AllowUnencrypted $false -ErrorAction SilentlyContinue\nSet-Item WSMan:\\localhost\\Client\\Auth\\Basic $false -ErrorAction SilentlyContinue" } },
    { "id": "NET-09", "domain": "Network Security", "type": "automated", "check": "listening_services", "severity": "low",
      "title": "No unexpected inbound listening services",
      "description": "Inventory of TCP listeners on non-loopback addresses; flags file-sharing/P2P/telnet/FTP/VNC style ports.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(A)"], "pci": ["1.2.5", "2.2.4"], "csf": ["ID.AM-03"], "n171": ["3.4.7", "3.13.6"], "cis": [] },
      "remediation": { "summary": "Review listener inventory; stop/uninstall unneeded services and block inbound ports.", "manual": "See findings detail for process/port list." } },
    { "id": "NET-10", "domain": "Network Security", "type": "automated", "check": "wifi_security", "severity": "medium",
      "title": "Saved Wi-Fi profiles use WPA2/WPA3 (no open or WEP networks)",
      "description": "PCI 4.2.1.2 / 2.3.1 wireless requirements.",
      "frameworks": { "hipaa": ["164.312(e)(1)"], "pci": ["2.3.1", "4.2.1.2"], "csf": ["PR.DS-02"], "n171": ["3.1.16", "3.1.17"], "cis": [] },
      "remediation": { "summary": "Delete open/WEP profiles.", "manual": "netsh wlan delete profile name=\"<profile>\" for each flagged profile." } },

    { "id": "LOG-01", "domain": "Logging & Monitoring", "type": "automated", "check": "audit_policy", "severity": "high",
      "title": "Advanced audit policy captures logon, account management, policy change, and privilege use",
      "description": "PCI 10.2 event categories; HIPAA audit controls 164.312(b).",
      "frameworks": { "hipaa": ["164.312(b)", "164.308(a)(1)(ii)(D)"], "pci": ["10.2.1", "10.2.1.1-7"], "csf": ["DE.CM-01", "DE.CM-03"], "n171": ["3.3.1", "3.3.2"], "cis": ["17.1.1", "17.2.x", "17.5.x", "17.7.x", "17.8.1"] },
      "remediation": { "summary": "Apply the CIS L1 audit baseline.",
        "script": "auditpol /set /subcategory:\"Credential Validation\" /success:enable /failure:enable\nauditpol /set /subcategory:\"Security Group Management\" /success:enable /failure:enable\nauditpol /set /subcategory:\"User Account Management\" /success:enable /failure:enable\nauditpol /set /subcategory:\"Logon\" /success:enable /failure:enable\nauditpol /set /subcategory:\"Logoff\" /success:enable\nauditpol /set /subcategory:\"Account Lockout\" /success:enable /failure:enable\nauditpol /set /subcategory:\"Special Logon\" /success:enable\nauditpol /set /subcategory:\"Audit Policy Change\" /success:enable /failure:enable\nauditpol /set /subcategory:\"Authentication Policy Change\" /success:enable\nauditpol /set /subcategory:\"Sensitive Privilege Use\" /success:enable /failure:enable\nauditpol /set /subcategory:\"Process Creation\" /success:enable\nauditpol /set /subcategory:\"Removable Storage\" /success:enable /failure:enable\nauditpol /set /subcategory:\"Security State Change\" /success:enable\nauditpol /set /subcategory:\"Security System Extension\" /success:enable\nauditpol /set /subcategory:\"System Integrity\" /success:enable /failure:enable\nSet-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' SCENoApplyLegacyAuditPolicy 1 -Type DWord" } },
    { "id": "LOG-02", "domain": "Logging & Monitoring", "type": "automated", "check": "eventlog_size", "severity": "medium",
      "title": "Security event log ≥ 196 MB; Application/System ≥ 32 MB; retention not overwriting daily",
      "description": "Adequate local retention until logs are forwarded (PCI 10.5.1: 12 months, 3 months immediately available).",
      "frameworks": { "hipaa": ["164.312(b)", "164.316(b)(2)(i)"], "pci": ["10.5.1"], "csf": ["DE.CM-01"], "n171": ["3.3.1"], "cis": ["18.10.25.1.2", "18.10.25.2.2", "18.10.25.4.2"] },
      "remediation": { "summary": "Increase event log sizes.", "script": "wevtutil sl Security /ms:1073741824\nwevtutil sl Application /ms:67108864\nwevtutil sl System /ms:67108864" } },
    { "id": "LOG-03", "domain": "Logging & Monitoring", "type": "automated", "check": "ps_logging", "severity": "medium",
      "title": "PowerShell script block logging and module logging enabled",
      "description": "Captures attacker tradecraft executed via PowerShell.",
      "frameworks": { "hipaa": ["164.312(b)"], "pci": ["10.2.1.7"], "csf": ["DE.CM-01"], "n171": ["3.3.1"], "cis": ["18.10.87.1", "18.10.87.2"] },
      "remediation": { "summary": "Enable script block + module logging.", "script": "New-Item 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging' EnableScriptBlockLogging 1 -Type DWord\nNew-Item 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging\\ModuleNames' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging' EnableModuleLogging 1 -Type DWord\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging\\ModuleNames' '*' '*'" } },
    { "id": "LOG-04", "domain": "Logging & Monitoring", "type": "automated", "check": "time_sync", "severity": "medium",
      "title": "Time synchronization configured and within 5 minutes of reference",
      "description": "PCI 10.6 requires synchronized, accurate time for log correlation.",
      "frameworks": { "hipaa": ["164.312(b)"], "pci": ["10.6.1", "10.6.2"], "csf": ["DE.CM-01"], "n171": ["3.3.7"], "cis": ["18.9.51.1.1"] },
      "remediation": { "summary": "Configure w32time against time.windows.com / domain hierarchy.", "script": "w32tm /config /manualpeerlist:\"time.windows.com,0x9\" /syncfromflags:manual /reliable:no /update\nSet-Service w32time -StartupType Automatic; Restart-Service w32time\nw32tm /resync /nowait" } },
    { "id": "LOG-05", "domain": "Logging & Monitoring", "type": "automated", "check": "log_forwarding", "severity": "medium",
      "title": "Logs forwarded to a central collector (SIEM / MDE / RMM / WEF)",
      "description": "Detects Windows Event Forwarding subscription, Microsoft Defender for Endpoint sensor, Azure Monitor Agent, or common SIEM/RMM agents.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(D)", "164.312(b)"], "pci": ["10.3.3", "10.4.1"], "csf": ["DE.CM-01", "DE.AE-03"], "n171": ["3.3.4", "3.3.8"], "cis": ["18.10.26.x"] },
      "remediation": { "summary": "Onboard to Defender for Endpoint / your SIEM and enable WEF.", "manual": "Deploy the MDE onboarding package or SIEM agent via RMM." } },

    { "id": "HARD-01", "domain": "System Hardening", "type": "automated", "check": "autorun_disabled", "severity": "medium",
      "title": "AutoRun/AutoPlay disabled for all drives",
      "description": "Prevents automatic execution from removable media.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["5.2.1"], "csf": ["PR.PS-01"], "n171": ["3.8.7"], "cis": ["18.10.7.1", "18.10.7.2", "18.10.7.3"] },
      "remediation": { "summary": "Disable AutoRun.", "script": "New-Item 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' NoDriveTypeAutoRun 255 -Type DWord\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' NoAutorun 1 -Type DWord" } },
    { "id": "HARD-02", "domain": "System Hardening", "type": "automated", "check": "anon_enum", "severity": "medium",
      "title": "Anonymous enumeration of SAM accounts and shares restricted",
      "description": "CIS 2.3.10.x; prevents unauthenticated account discovery.",
      "frameworks": { "hipaa": ["164.312(a)(1)"], "pci": ["2.2.4"], "csf": ["PR.AA-01"], "n171": ["3.1.1"], "cis": ["2.3.10.2", "2.3.10.3"] },
      "remediation": { "summary": "Restrict anonymous.", "script": "Set-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' RestrictAnonymous 1 -Type DWord\nSet-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' RestrictAnonymousSAM 1 -Type DWord\nSet-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' EveryoneIncludesAnonymous 0 -Type DWord" } },
    { "id": "HARD-03", "domain": "System Hardening", "type": "automated", "check": "lm_hash_ntlmv2", "severity": "high",
      "title": "LM hash storage disabled and NTLMv2-only authentication",
      "description": "LM/NTLMv1 hashes are trivially cracked.",
      "frameworks": { "hipaa": ["164.312(d)", "164.312(a)(2)(iv)"], "pci": ["8.3.2"], "csf": ["PR.AA-01"], "n171": ["3.5.10"], "cis": ["2.3.11.5", "2.3.11.7"] },
      "remediation": { "summary": "NoLMHash=1, LmCompatibilityLevel=5.", "script": "Set-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' NoLMHash 1 -Type DWord\nSet-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' LmCompatibilityLevel 5 -Type DWord" } },
    { "id": "HARD-04", "domain": "System Hardening", "type": "automated", "check": "wdigest", "severity": "high",
      "title": "WDigest cleartext credential caching disabled",
      "description": "Prevents Mimikatz recovery of plaintext passwords from LSASS.",
      "frameworks": { "hipaa": ["164.312(a)(2)(iv)"], "pci": ["8.3.2"], "csf": ["PR.AA-01"], "n171": ["3.5.10"], "cis": ["18.4.7"] },
      "remediation": { "summary": "UseLogonCredential=0.", "script": "New-Item 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest' UseLogonCredential 0 -Type DWord" } },
    { "id": "HARD-05", "domain": "System Hardening", "type": "automated", "check": "lsa_protection", "severity": "medium",
      "title": "LSA protection (RunAsPPL) and Credential Guard enabled",
      "description": "Hardens LSASS against credential dumping.",
      "frameworks": { "hipaa": ["164.312(a)(2)(iv)"], "pci": ["8.3.2"], "csf": ["PR.AA-01"], "n171": ["3.5.10"], "cis": ["18.4.6", "18.9.5.x"] },
      "remediation": { "summary": "Enable RunAsPPL; enable Credential Guard where hardware supports it.", "script": "Set-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' RunAsPPL 1 -Type DWord\nNew-Item 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard' EnableVirtualizationBasedSecurity 1 -Type DWord\nSet-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' LsaCfgFlags 1 -Type DWord" } },
    { "id": "HARD-06", "domain": "System Hardening", "type": "automated", "check": "psv2_disabled", "severity": "medium",
      "title": "PowerShell 2.0 engine removed",
      "description": "PS v2 bypasses script block logging, AMSI, and constrained language mode.",
      "frameworks": { "hipaa": ["164.312(b)"], "pci": ["2.2.4"], "csf": ["PR.PS-01"], "n171": ["3.4.7"], "cis": ["18.10.87.x"] },
      "remediation": { "summary": "Remove the feature.", "script": "Disable-WindowsOptionalFeature -Online -FeatureName MicrosoftWindowsPowerShellV2Root -NoRestart -ErrorAction SilentlyContinue" } },
    { "id": "HARD-07", "domain": "System Hardening", "type": "automated", "check": "dep_enabled", "severity": "low",
      "title": "Data Execution Prevention set to OptOut or AlwaysOn",
      "description": "Memory-protection baseline.",
      "frameworks": { "hipaa": ["164.312(c)(1)"], "pci": ["2.2.4"], "csf": ["PR.PS-01"], "n171": ["3.14.2"], "cis": ["18.10.x"] },
      "remediation": { "summary": "Set DEP OptOut.", "script": "bcdedit /set nx OptOut | Out-Null" } },
    { "id": "HARD-08", "domain": "System Hardening", "type": "automated", "check": "unquoted_services", "severity": "low",
      "title": "No unquoted service paths with spaces",
      "description": "Classic local privilege-escalation weakness.",
      "frameworks": { "hipaa": ["164.312(a)(1)"], "pci": ["6.3.1"], "csf": ["PR.PS-01"], "n171": ["3.4.6"], "cis": [] },
      "remediation": { "summary": "Quote the ImagePath of listed services.", "manual": "Fix ImagePath in HKLM\\SYSTEM\\CurrentControlSet\\Services\\<svc> for each service listed in findings." } },
    { "id": "HARD-09", "domain": "System Hardening", "type": "automated", "check": "cached_logons", "severity": "low",
      "title": "Cached domain logons limited (≤ 4)",
      "description": "Reduces offline credential-cracking exposure on lost laptops.",
      "frameworks": { "hipaa": ["164.312(a)(2)(iv)"], "pci": ["8.3.2"], "csf": ["PR.AA-01"], "n171": ["3.5.10"], "cis": ["2.3.7.x"] },
      "remediation": { "summary": "CachedLogonsCount=4.", "script": "Set-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon' CachedLogonsCount '4'" } },
    { "id": "HARD-10", "domain": "System Hardening", "type": "automated", "check": "legal_notice", "severity": "low",
      "title": "Interactive logon banner configured",
      "description": "Notice of monitoring and authorized-use — supports HIPAA sanction policy and 800-171 3.1.9.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(C)"], "pci": ["12.6.1"], "csf": ["GV.PO-01"], "n171": ["3.1.9"], "cis": ["2.3.7.4", "2.3.7.5"] },
      "remediation": { "summary": "Set legal notice caption and text.", "script": "$k='HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System'\nSet-ItemProperty $k legalnoticecaption 'Authorized Use Only'\nSet-ItemProperty $k legalnoticetext 'This system is for authorized users only. Activity is monitored and recorded. Unauthorized access is prohibited and may be prosecuted.'" } },
    { "id": "HARD-11", "domain": "System Hardening", "type": "automated", "check": "admin_shares_ipv6", "severity": "low",
      "title": "Unnecessary features disabled (Windows Script Host for users, optional legacy features)",
      "description": "Reduces script-based malware execution surface.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)"], "pci": ["2.2.4"], "csf": ["PR.PS-01"], "n171": ["3.4.6"], "cis": [] },
      "remediation": { "summary": "Disable WSH.", "script": "New-Item 'HKLM:\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings' Enabled 0 -Type DWord" } },

    { "id": "DATA-01", "domain": "Data Protection", "type": "automated", "check": "phi_discovery", "severity": "critical",
      "title": "No unprotected PHI / cardholder data at rest in user-accessible files",
      "description": "Content discovery across user profiles, shares, Desktop/Documents/Downloads, mail exports, and temp folders for SSN, MRN, DOB+name, ICD-10, NPI, health-plan IDs, card PANs (Luhn-validated), and clinical keywords in .txt/.csv/.docx/.xlsx/.pdf/.rtf/.eml/.msg/.json/.xml/.log. Only file path, pattern type, hit count, and a masked sample are reported — never the data itself.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(A)", "164.310(d)(2)(i)", "164.312(a)(2)(iv)"], "pci": ["3.2.1", "3.3.1", "3.4.1", "12.5.2"], "csf": ["ID.AM-07", "PR.DS-01"], "n171": ["3.8.1", "3.8.3", "3.13.16"], "cis": [] },
      "remediation": { "summary": "Move flagged files into the EHR/PMS or an encrypted, access-controlled repository; securely delete local copies; disable local saves in browser/email; enable Purview DLP.", "manual": "Review each flagged path in findings detail with the client. Do not delete without owner confirmation." } },
    { "id": "DATA-02", "domain": "Data Protection", "type": "automated", "check": "cloud_sync_clients", "severity": "low",
      "title": "Personal cloud-sync clients not present (Dropbox, Google Drive personal, iCloud, Box personal)",
      "description": "Uncontrolled sync channels move ePHI/CHD outside covered systems.",
      "frameworks": { "hipaa": ["164.308(a)(3)(i)", "164.312(e)(1)"], "pci": ["12.3.1", "3.4.2"], "csf": ["PR.DS-01"], "n171": ["3.1.20", "3.1.21"], "cis": [] },
      "remediation": { "summary": "Uninstall personal sync clients; standardize on business OneDrive/SharePoint with DLP.", "manual": "Uninstall listed applications." } },
    { "id": "DATA-03", "domain": "Data Protection", "type": "automated", "check": "browser_password_store", "severity": "low",
      "title": "Browser built-in password managers disabled by policy",
      "description": "Credentials for clinical/payment systems should live in an enterprise password manager, not the browser profile.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(D)"], "pci": ["8.3.2"], "csf": ["PR.AA-01"], "n171": ["3.5.10"], "cis": [] },
      "remediation": { "summary": "Disable password saving in Edge/Chrome via policy.", "script": "New-Item 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Edge' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Edge' PasswordManagerEnabled 0 -Type DWord\nNew-Item 'HKLM:\\SOFTWARE\\Policies\\Google\\Chrome' -Force | Out-Null\nSet-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Google\\Chrome' PasswordManagerEnabled 0 -Type DWord" } },
    { "id": "DATA-04", "domain": "Data Protection", "type": "automated", "check": "backup_agent", "severity": "high",
      "title": "Endpoint backup or known-good data-protection agent present",
      "description": "HIPAA contingency plan 164.308(a)(7) requires retrievable exact copies of ePHI. Detects OneDrive Known Folder Move, Veeam, Datto, Acronis, Backblaze, Windows Backup.",
      "frameworks": { "hipaa": ["164.308(a)(7)(ii)(A)", "164.310(d)(2)(iv)"], "pci": ["12.10.1"], "csf": ["PR.DS-11", "RC.RP-01"], "n171": ["3.8.9"], "cis": [] },
      "remediation": { "summary": "Deploy the managed backup agent or enable OneDrive Known Folder Move.", "manual": "Deploy via RMM." } },

    { "id": "ADM-01", "domain": "Administrative Safeguards", "type": "manual", "severity": "critical",
      "title": "Formal, documented security risk analysis completed within the last 12 months",
      "question": "Has the organization completed and documented an enterprise-wide security risk analysis (identifying where ePHI/CHD is created, received, stored, transmitted, and the threats to it) within the last 12 months?",
      "evidenceHint": "Risk analysis report, risk register, date and author.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(A)"], "pci": ["12.3.1"], "csf": ["ID.RA-01", "ID.RA-05"], "n171": ["3.11.1"], "cis": [] },
      "remediation": { "summary": "Conduct a risk analysis using NIST SP 800-30 / HHS SRA Tool; TEKNIK can deliver this as a service." } },
    { "id": "ADM-02", "domain": "Administrative Safeguards", "type": "manual", "severity": "high",
      "title": "Risk management plan with tracked remediation",
      "question": "Is there a documented risk management plan that tracks identified risks to closure with owners and target dates?",
      "evidenceHint": "Risk treatment plan / POA&M.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(B)"], "pci": ["12.3.1"], "csf": ["ID.RA-06", "GV.RM-01"], "n171": ["3.12.2"], "cis": [] },
      "remediation": { "summary": "Maintain a POA&M reviewed quarterly." } },
    { "id": "ADM-03", "domain": "Administrative Safeguards", "type": "manual", "severity": "high",
      "title": "Designated Security Official / compliance owner",
      "question": "Has a specific individual been formally designated as responsible for security (HIPAA Security Official) and for PCI compliance?",
      "evidenceHint": "Appointment letter, org chart, policy naming the role.",
      "frameworks": { "hipaa": ["164.308(a)(2)"], "pci": ["12.4.1", "12.1.4"], "csf": ["GV.RR-02"], "n171": [], "cis": [] },
      "remediation": { "summary": "Formally assign the role in writing and in the security policy." } },
    { "id": "ADM-04", "domain": "Administrative Safeguards", "type": "manual", "severity": "high",
      "title": "Written information security policies approved and reviewed annually",
      "question": "Are written security policies and procedures (acceptable use, access control, incident response, data handling, sanctions) approved by management and reviewed at least annually?",
      "evidenceHint": "Policy set with approval/review dates.",
      "frameworks": { "hipaa": ["164.316(a)", "164.316(b)(2)(iii)"], "pci": ["12.1.1", "12.1.2"], "csf": ["GV.PO-01", "GV.PO-02"], "n171": ["3.12.4"], "cis": [] },
      "remediation": { "summary": "Adopt a policy set (TEKNIK template library) and calendar an annual review." } },
    { "id": "ADM-05", "domain": "Administrative Safeguards", "type": "manual", "severity": "high",
      "title": "Workforce security awareness training (annual + onboarding)",
      "question": "Do all workforce members complete security awareness training at hire and at least annually, including phishing, PHI/CHD handling, and password hygiene, with attendance records kept?",
      "evidenceHint": "Training completion report / LMS export.",
      "frameworks": { "hipaa": ["164.308(a)(5)(i)", "164.308(a)(5)(ii)(A)"], "pci": ["12.6.1", "12.6.3"], "csf": ["PR.AT-01"], "n171": ["3.2.1", "3.2.2"], "cis": [] },
      "remediation": { "summary": "Enroll staff in a managed awareness platform with simulated phishing." } },
    { "id": "ADM-06", "domain": "Administrative Safeguards", "type": "manual", "severity": "medium",
      "title": "Sanction policy for workforce violations",
      "question": "Is there a documented sanction policy applied to workforce members who fail to comply with security policies?",
      "evidenceHint": "HR policy section / employee handbook.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(C)"], "pci": ["12.1.3"], "csf": ["GV.RR-04"], "n171": [], "cis": [] },
      "remediation": { "summary": "Add a sanctions clause to the handbook and have staff acknowledge it." } },
    { "id": "ADM-07", "domain": "Administrative Safeguards", "type": "manual", "severity": "high",
      "title": "Access authorization, review, and termination procedures",
      "question": "Are user access rights granted based on role, reviewed at least every 6 months, and revoked within 24 hours of termination or role change?",
      "evidenceHint": "Access review log, offboarding checklist.",
      "frameworks": { "hipaa": ["164.308(a)(3)(ii)(B)", "164.308(a)(3)(ii)(C)", "164.308(a)(4)(ii)(C)"], "pci": ["7.2.4", "8.2.4", "8.2.5"], "csf": ["PR.AA-01", "PR.AA-05"], "n171": ["3.1.1", "3.1.2"], "cis": [] },
      "remediation": { "summary": "Implement a joiner/mover/leaver checklist with semi-annual access reviews." } },
    { "id": "ADM-08", "domain": "Administrative Safeguards", "type": "manual", "severity": "critical",
      "title": "Multi-factor authentication enforced for email, remote access, and all admin access",
      "question": "Is MFA enforced for all users on email/M365, VPN/remote access, EHR/PMS cloud apps, and for every administrative account?",
      "evidenceHint": "Conditional Access policy export, MFA registration report.",
      "frameworks": { "hipaa": ["164.312(d)"], "pci": ["8.4.1", "8.4.2", "8.4.3"], "csf": ["PR.AA-03"], "n171": ["3.5.3"], "cis": [] },
      "remediation": { "summary": "Enforce MFA via Entra Conditional Access; block legacy auth." } },
    { "id": "ADM-09", "domain": "Administrative Safeguards", "type": "manual", "severity": "critical",
      "title": "Incident response plan tested annually",
      "question": "Is there a written incident response plan covering breach identification, containment, HIPAA breach notification (60 days) / PCI (immediate to brands), and has it been tested (tabletop) in the last 12 months?",
      "evidenceHint": "IR plan, tabletop exercise report.",
      "frameworks": { "hipaa": ["164.308(a)(6)(i)", "164.308(a)(6)(ii)", "164.404"], "pci": ["12.10.1", "12.10.2"], "csf": ["RS.MA-01", "GV.PO-01"], "n171": ["3.6.1", "3.6.2"], "cis": [] },
      "remediation": { "summary": "Adopt an IR plan and run an annual tabletop with TEKNIK." } },
    { "id": "ADM-10", "domain": "Administrative Safeguards", "type": "manual", "severity": "critical",
      "title": "Contingency plan: backups tested, disaster recovery, emergency mode operations",
      "question": "Are backups of ePHI/critical data performed, encrypted, stored off-site/immutable, and restore-tested at least quarterly, with a written DR plan and defined RTO/RPO?",
      "evidenceHint": "Backup job reports, restore test log, DR plan.",
      "frameworks": { "hipaa": ["164.308(a)(7)(i)", "164.308(a)(7)(ii)(A)-(E)"], "pci": ["12.10.1"], "csf": ["PR.DS-11", "RC.RP-01"], "n171": ["3.8.9"], "cis": [] },
      "remediation": { "summary": "Managed BCDR with quarterly restore tests documented." } },
    { "id": "ADM-11", "domain": "Administrative Safeguards", "type": "manual", "severity": "high",
      "title": "Business Associate Agreements / third-party service provider management",
      "question": "Are signed BAAs in place with every vendor that handles ePHI, and is a list of PCI service providers maintained with their compliance status reviewed annually?",
      "evidenceHint": "BAA register, vendor list with AOC dates.",
      "frameworks": { "hipaa": ["164.308(b)(1)", "164.314(a)"], "pci": ["12.8.1", "12.8.2", "12.8.4", "12.8.5"], "csf": ["GV.SC-04", "GV.SC-07"], "n171": [], "cis": [] },
      "remediation": { "summary": "Build a vendor register; collect BAAs and AOCs." } },
    { "id": "ADM-12", "domain": "Administrative Safeguards", "type": "manual", "severity": "medium",
      "title": "Periodic technical and non-technical evaluation",
      "question": "Is a security evaluation (like this assessment) performed at least annually and after significant environmental or operational changes?",
      "evidenceHint": "Prior assessment reports.",
      "frameworks": { "hipaa": ["164.308(a)(8)"], "pci": ["12.4.2"], "csf": ["ID.IM-01"], "n171": ["3.12.1", "3.12.3"], "cis": [] },
      "remediation": { "summary": "Schedule annual assessment." } },
    { "id": "ADM-13", "domain": "Administrative Safeguards", "type": "manual", "severity": "medium",
      "title": "Asset inventory of all devices and systems handling ePHI/CHD",
      "question": "Is there a current inventory of all workstations, servers, mobile devices, and applications that store, process, or transmit ePHI/CHD?",
      "evidenceHint": "Asset register / RMM export.",
      "frameworks": { "hipaa": ["164.310(d)(2)(iii)"], "pci": ["12.5.1", "9.5.1.1"], "csf": ["ID.AM-01", "ID.AM-02"], "n171": ["3.4.1"], "cis": [] },
      "remediation": { "summary": "Maintain inventory in RMM; reconcile quarterly." } },
    { "id": "ADM-14", "domain": "Administrative Safeguards", "type": "manual", "severity": "medium",
      "title": "Documentation retained 6 years and available to workforce",
      "question": "Are security policies, procedures, risk analyses, and related records retained for at least 6 years and available to responsible personnel?",
      "evidenceHint": "Document repository listing.",
      "frameworks": { "hipaa": ["164.316(b)(1)", "164.316(b)(2)"], "pci": ["12.1.1"], "csf": ["GV.PO-01"], "n171": [], "cis": [] },
      "remediation": { "summary": "Store in SharePoint with retention labels." } },

    { "id": "PHY-01", "domain": "Physical Safeguards", "type": "manual", "severity": "high",
      "title": "Facility access controls",
      "question": "Are areas containing workstations, servers, network equipment, and paper records physically secured (locks, badge, alarm) with visitor logging and after-hours controls?",
      "evidenceHint": "Facility security plan, visitor log sample, photos.",
      "frameworks": { "hipaa": ["164.310(a)(1)", "164.310(a)(2)(ii)"], "pci": ["9.2.1", "9.3.1", "9.3.2"], "csf": ["PR.AA-06"], "n171": ["3.10.1", "3.10.3"], "cis": [] },
      "remediation": { "summary": "Document facility access plan; add visitor log." } },
    { "id": "PHY-02", "domain": "Physical Safeguards", "type": "manual", "severity": "medium",
      "title": "Workstation use and positioning",
      "question": "Are workstation screens positioned or shielded so ePHI/CHD is not visible to unauthorized persons, and are workstation-use rules documented?",
      "evidenceHint": "Workstation use policy; privacy screens.",
      "frameworks": { "hipaa": ["164.310(b)", "164.310(c)"], "pci": ["9.2.1"], "csf": ["PR.AA-06"], "n171": ["3.10.5"], "cis": [] },
      "remediation": { "summary": "Privacy filters for public-facing stations; policy acknowledgement." } },
    { "id": "PHY-03", "domain": "Physical Safeguards", "type": "manual", "severity": "high",
      "title": "Device and media disposal / reuse",
      "question": "Are drives and media containing ePHI/CHD securely wiped (NIST 800-88) or destroyed before disposal or reuse, with certificates of destruction retained?",
      "evidenceHint": "Disposal log, certificates of destruction.",
      "frameworks": { "hipaa": ["164.310(d)(2)(i)", "164.310(d)(2)(ii)"], "pci": ["9.4.7", "3.2.1"], "csf": ["PR.DS-01"], "n171": ["3.8.3"], "cis": [] },
      "remediation": { "summary": "Use a certified ITAD vendor; keep certificates." } },
    { "id": "PHY-04", "domain": "Physical Safeguards", "type": "manual", "severity": "medium",
      "title": "Portable media and mobile device controls",
      "question": "Are laptops, phones, and removable media that touch ePHI/CHD inventoried, encrypted, and covered by remote-wipe capability?",
      "evidenceHint": "MDM enrollment report.",
      "frameworks": { "hipaa": ["164.310(d)(1)", "164.312(a)(2)(iv)"], "pci": ["9.4.1", "9.4.2"], "csf": ["PR.DS-01"], "n171": ["3.8.7", "3.1.18"], "cis": [] },
      "remediation": { "summary": "Enroll all mobile devices in Intune with encryption and wipe policies." } },
    { "id": "PHY-05", "domain": "Physical Safeguards", "type": "manual", "severity": "medium",
      "title": "Point-of-interaction device protection (PCI)",
      "question": "If card-present payments are accepted: are POI terminals inventoried, periodically inspected for tampering/skimmers, and are staff trained to recognize tampering? (Answer N/A if no card-present payments.)",
      "evidenceHint": "Terminal inventory, inspection log.",
      "frameworks": { "hipaa": [], "pci": ["9.5.1", "9.5.1.1", "9.5.1.2", "9.5.1.3"], "csf": ["PR.AA-06"], "n171": [], "cis": [] },
      "remediation": { "summary": "Maintain terminal inventory and monthly inspection checklist." } },

    { "id": "PCI-01", "domain": "Payment Environment", "type": "manual", "severity": "critical",
      "title": "Cardholder data environment scoped and segmented",
      "question": "Is the cardholder data environment (systems that store, process, or transmit card data) defined and documented, and segmented from the rest of the network (or fully outsourced to a validated P2PE/hosted solution)?",
      "evidenceHint": "Network diagram, data-flow diagram, segmentation test.",
      "frameworks": { "hipaa": [], "pci": ["1.2.4", "1.3.1", "12.5.2"], "csf": ["PR.IR-01"], "n171": ["3.13.2"], "cis": [] },
      "remediation": { "summary": "Document CDE and data flows; validate segmentation." } },
    { "id": "PCI-02", "domain": "Payment Environment", "type": "manual", "severity": "critical",
      "title": "No storage of sensitive authentication data; PAN masked and not stored locally",
      "question": "Does the organization confirm that full card numbers, CVV, or track data are never written down, emailed, or stored on workstations, and that PAN is masked on displays/receipts?",
      "evidenceHint": "Data-handling policy, sample receipts.",
      "frameworks": { "hipaa": [], "pci": ["3.3.1", "3.4.1", "3.2.1"], "csf": ["PR.DS-01"], "n171": [], "cis": [] },
      "remediation": { "summary": "Prohibit manual card capture; use tokenized processor." } },
    { "id": "PCI-03", "domain": "Payment Environment", "type": "manual", "severity": "high",
      "title": "Quarterly ASV external vulnerability scans and annual penetration test",
      "question": "Are external vulnerability scans performed quarterly by an Approved Scanning Vendor with passing results, and is a penetration test performed at least annually (where required by SAQ type)?",
      "evidenceHint": "ASV scan reports, pen-test report.",
      "frameworks": { "hipaa": ["164.308(a)(8)"], "pci": ["11.3.2", "11.4.1"], "csf": ["ID.RA-01"], "n171": ["3.11.2"], "cis": [] },
      "remediation": { "summary": "Engage ASV; schedule annual pen test." } },
    { "id": "PCI-04", "domain": "Payment Environment", "type": "manual", "severity": "high",
      "title": "Internal vulnerability scanning with authenticated scans",
      "question": "Are internal vulnerability scans run at least quarterly (authenticated) and high/critical findings remediated and rescanned?",
      "evidenceHint": "Vulnerability scan reports.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(A)"], "pci": ["11.3.1", "11.3.1.2"], "csf": ["ID.RA-01"], "n171": ["3.11.2", "3.11.3"], "cis": [] },
      "remediation": { "summary": "Deploy vulnerability management (e.g., Defender Vulnerability Management)." } },
    { "id": "PCI-05", "domain": "Payment Environment", "type": "manual", "severity": "high",
      "title": "Log review and retention (12 months, 3 months online)",
      "question": "Are security logs reviewed at least daily (automated alerting acceptable) and retained for 12 months with 3 months immediately available?",
      "evidenceHint": "SIEM retention config, alert samples.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(D)", "164.312(b)"], "pci": ["10.4.1", "10.5.1"], "csf": ["DE.CM-01", "DE.AE-02"], "n171": ["3.3.1", "3.3.5"], "cis": [] },
      "remediation": { "summary": "Managed SIEM/MDR with 12-month retention." } },
    { "id": "PCI-06", "domain": "Payment Environment", "type": "manual", "severity": "medium",
      "title": "Change management and secure configuration standards",
      "question": "Are configuration standards (CIS/vendor hardening) documented for all system types, and are changes to in-scope systems approved and recorded?",
      "evidenceHint": "Configuration standard, change log.",
      "frameworks": { "hipaa": ["164.308(a)(1)(ii)(B)"], "pci": ["2.2.1", "6.5.1", "6.5.2"], "csf": ["PR.PS-01", "ID.AM-08"], "n171": ["3.4.1", "3.4.3"], "cis": [] },
      "remediation": { "summary": "Adopt CIS baselines; ticket-based change log." } },
    { "id": "PCI-07", "domain": "Payment Environment", "type": "manual", "severity": "medium",
      "title": "Email/web protection and anti-phishing",
      "question": "Is inbound email filtered for malware/phishing (with SPF, DKIM, DMARC enforced) and web traffic filtered (DNS/URL filtering) on all workstations?",
      "evidenceHint": "DMARC record, mail-filter policy, DNS filter dashboard.",
      "frameworks": { "hipaa": ["164.308(a)(5)(ii)(B)", "164.312(e)(1)"], "pci": ["5.4.1"], "csf": ["PR.PS-05", "DE.CM-01"], "n171": ["3.13.1", "3.14.2"], "cis": [] },
      "remediation": { "summary": "Enforce DMARC p=reject; deploy DNS filtering." } },
    { "id": "PCI-08", "domain": "Payment Environment", "type": "manual", "severity": "medium",
      "title": "Encryption of PHI/CHD in transit (email, file transfer, remote access)",
      "question": "Is ePHI/CHD sent externally only via encrypted channels (TLS-enforced email encryption, secure portal, VPN), never via unencrypted email, SMS, or fax-to-email without controls?",
      "evidenceHint": "Email encryption policy/rules, VPN config.",
      "frameworks": { "hipaa": ["164.312(e)(1)", "164.312(e)(2)(ii)"], "pci": ["4.2.1", "4.2.2"], "csf": ["PR.DS-02"], "n171": ["3.13.8"], "cis": [] },
      "remediation": { "summary": "Enable Purview Message Encryption rules for PHI keywords." } }
  ]
}
;

export const controlsById = Object.fromEntries(catalog.controls.map(c => [c.id, c]));
export const automatedControls = catalog.controls.filter(c => c.type === 'automated');
export const manualControls = catalog.controls.filter(c => c.type === 'manual');
